# Generated by Django 4.2.7 on 2024-10-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fistname',
            new_name='firstname',
        ),
    ]
